# Generated by Django 3.2.24 on 2024-03-06 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=50)),
                ('summary', models.TextField(blank=True, null=True)),
                ('picture_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDate',
            fields=[
                ('date_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_time', models.TimeField()),
                ('order_date', models.DateField()),
                ('order_week', models.IntegerField()),
                ('order_month', models.IntegerField()),
                ('order_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.IntegerField()),
                ('order_id', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderapp.orderdate')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderapp.menu')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderapp.supplier')),
            ],
            options={
                'unique_together': {('table_id', 'supplier', 'menu', 'date', 'order_id')},
            },
        ),
    ]
