# Generated by Django 3.2.24 on 2024-03-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_auto_20240308_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='picture_address',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
