# Generated by Django 3.2.25 on 2024-04-09 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0004_alter_menu_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordertable',
            old_name='date',
            new_name='date_id',
        ),
        migrations.RenameField(
            model_name='ordertable',
            old_name='menu',
            new_name='menu_id',
        ),
        migrations.RenameField(
            model_name='ordertable',
            old_name='supplier',
            new_name='supplier_id',
        ),
        migrations.AlterUniqueTogether(
            name='ordertable',
            unique_together={('table_id', 'supplier_id', 'menu_id', 'date_id', 'order_id')},
        ),
    ]
