# Generated by Django 3.2.25 on 2024-04-09 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0005_auto_20240409_0634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordertable',
            old_name='menu_id',
            new_name='menu',
        ),
        migrations.RenameField(
            model_name='ordertable',
            old_name='date_id',
            new_name='order_date',
        ),
        migrations.RenameField(
            model_name='ordertable',
            old_name='supplier_id',
            new_name='supplier',
        ),
        migrations.AlterUniqueTogether(
            name='ordertable',
            unique_together={('table_id', 'supplier', 'menu', 'order_date', 'order_id')},
        ),
    ]
