# Generated by Django 3.2.25 on 2024-04-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0006_auto_20240409_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='order_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Finished', 'Finished'), ('Cancelled', 'Cancelled')], max_length=50, null=True),
        ),
    ]
