# Generated by Django 3.2.25 on 2024-04-19 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0007_alter_ordertable_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orderapp.supplier'),
            preserve_default=False,
        ),
    ]
