# Generated by Django 3.2.25 on 2024-04-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0008_menu_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='picture_address',
            field=models.ImageField(blank=True, default='images/default_image.jpg', null=True, upload_to='images/'),
        ),
    ]
