# Generated by Django 3.2.25 on 2024-05-03 10:21

from django.db import migrations, models
import django.utils.timezone
import orderapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0009_alter_menu_picture_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='order_date_real',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ordertable',
            name='order_time',
            field=models.TimeField(default=orderapp.models.current_time),
        ),
    ]
