# Generated by Django 3.2.25 on 2024-06-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0010_auto_20240503_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='inStock',
            field=models.BooleanField(default=True),
        ),
    ]
