# Generated by Django 3.2.25 on 2024-08-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0011_menu_instock'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
