# Generated by Django 3.2.25 on 2024-08-20 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0014_auto_20240820_0454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordertable',
            old_name='cost_price',
            new_name='total_cost',
        ),
    ]
