# Generated by Django 3.2.25 on 2024-08-20 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0015_rename_cost_price_ordertable_total_cost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
